/**
 * /robots.txt — generated by Next.js's App-Router convention.
 *
 * Allows everything by default (we want to be discovered) and points
 * search engines at /sitemap.xml. The /api/ disallow is defensive —
 * the site does not currently expose any /api/ routes, but the
 * Server Action used by /play-with-me lives behind App Router's
 * internal action route handler, and there is no value to a search
 * engine indexing those.
 */

import type { MetadataRoute } from "next";

import { SITE_URL } from "@/lib/seo/site";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}