/**
 * /sitemap.xml — generated by Next.js's App-Router convention.
 *
 * Covers:
 *   - the four standard pages (/, /about, /play-with-me, /archive)
 *   - all 49 individual archive post pages
 *
 * `lastModified` for each archive post comes straight from the
 * frontmatter `publishedAt`. The archive is a finished body of work —
 * those dates are the truth. The four standard pages get the build
 * timestamp because they may receive small wording tweaks over time.
 *
 * `changeFrequency` and `priority` are honest reflections of how the
 * site behaves: the index-style pages may change a little, the
 * individual posts won't.
 */

import type { MetadataRoute } from "next";

import { loadAllArchivePosts } from "@/lib/archive/loader";
import { SITE_URL } from "@/lib/seo/site";

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const posts = loadAllArchivePosts();

  const standardEntries: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/about`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/play-with-me`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/archive`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.9,
    },
  ];

  const postEntries: MetadataRoute.Sitemap = posts.map((p) => ({
    url: `${SITE_URL}/archive/${p.slug}`,
    // publishedAt is a YYYY-MM-DD string in the frontmatter; new Date()
    // parses ISO-8601 reliably across runtimes.
    lastModified: new Date(p.publishedAt),
    changeFrequency: "yearly",
    priority: 0.7,
  }));

  return [...standardEntries, ...postEntries];
}